/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'ownerEmail' : IDL.Text,
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'mediaIds' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'listingId' : IDL.Nat,
  'buyerPhone' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createListing' : IDL.Func([PropertyListing], [IDL.Nat], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalListings' : IDL.Nat, 'totalUsers' : IDL.Nat })],
      ['query'],
    ),
  'getInquiriesForListing' : IDL.Func([IDL.Nat], [IDL.Vec(Inquiry)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'toggleAdActiveState' : IDL.Func([IDL.Nat], [], []),
  'updateAd' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'ownerEmail' : IDL.Text,
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'mediaIds' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'listingId' : IDL.Nat,
    'buyerPhone' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAd' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createListing' : IDL.Func([PropertyListing], [IDL.Nat], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'getActiveAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAllAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalListings' : IDL.Nat, 'totalUsers' : IDL.Nat })],
        ['query'],
      ),
    'getInquiriesForListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'toggleAdActiveState' : IDL.Func([IDL.Nat], [], []),
    'updateAd' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };