/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : bigint,
  'title' : string,
  'linkUrl' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'imageUrl' : string,
}
export interface Inquiry {
  'id' : bigint,
  'listingId' : bigint,
  'buyerPhone' : string,
  'message' : string,
  'timestamp' : bigint,
  'buyerName' : string,
}
export interface PropertyListing {
  'id' : bigint,
  'ownerEmail' : string,
  'title' : string,
  'propertyType' : string,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'mediaIds' : Array<string>,
  'price' : bigint,
  'location' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAd' : ActorMethod<[string, string, string], bigint>,
  'createListing' : ActorMethod<[PropertyListing], bigint>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'getActiveAds' : ActorMethod<[], Array<Ad>>,
  'getAllAds' : ActorMethod<[], Array<Ad>>,
  'getAllListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalStats' : ActorMethod<
    [],
    { 'totalListings' : bigint, 'totalUsers' : bigint }
  >,
  'getInquiriesForListing' : ActorMethod<[bigint], Array<Inquiry>>,
  'getListing' : ActorMethod<[bigint], PropertyListing>,
  'getMyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[bigint, string, string, string], bigint>,
  'toggleAdActiveState' : ActorMethod<[bigint], undefined>,
  'updateAd' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateListing' : ActorMethod<
    [bigint, string, string, bigint, string, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];